# Generated by Django 3.0.1 on 2019-12-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('image', models.FilePathField(path='C:\\Users\\Jodic\\Documents\\projects\\django_projects\\personal_site\\personal_site\\static/images')),
                ('link', models.URLField()),
            ],
        ),
    ]
