# Generated by Django 3.0.1 on 2019-12-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='link_text',
            field=models.CharField(default='Learn More', max_length=64),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.FilePathField(path='C:\\Users\\Jodic\\Documents\\projects\\django_projects\\personal_site\\personal_site\\main/static/images'),
        ),
    ]
