# Generated by Django 3.0.1 on 2019-12-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191230_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.FilePathField(path='C:\\Users\\Jodic\\Documents\\projects\\django_projects\\personal_site\\personal_site\\main\\static\\images'),
        ),
    ]
