# Generated by Django 3.0.1 on 2019-12-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191230_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image_charfieldpath',
            field=models.CharField(default='Path', max_length=128),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.CharField(default='Description', max_length=256),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(default='Title', max_length=128),
        ),
    ]
