# Generated by Django 3.0.1 on 2019-12-31 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191230_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='image_charfieldpath',
            new_name='image_path',
        ),
    ]
